name: "Java Version"
description: "Set the latest Java version for the current gradle version found in the project"

outputs:
  java-version:
    description: "Java version set"
    value: ${{ steps.current-java-version.outputs.java-version }}

runs:
  using: "composite"
  steps:
    - name: Install Python 3
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"

    - name: Try to reinstall dependencies
      run: pip install requests
      shell: pwsh

    - name: Execute command
      id: current-java-version
      run: python3 ${{ github.action_path }}/src/main.py ga
      shell: pwsh
