name: "Java Version"
description: "Set the latest Java version for the current gradle version found in the project"

outputs:
  java-version:
    description: "Java version set"
    value: ${{ steps.current-java-version.outputs.java-version }}

runs:
  using: "composite"
  steps:
    - name: Install Python 3
      uses: actions/setup-python@v1
      with:
        python-version: "3.x"

    - name: Try to reinstall dependancies
      run: pip install requests
      shell: bash

    - name: Execute command
      run: python ${{ github.action_path }}/main.py
      shell: bash

    - name: Output result
      id: current-java-version
      if: runner.os != 'Windows'
      run: echo "::set-output name=java-version::$?"
      shell: bash

    - id: current-java-version
      if: runner.os == 'Windows'
      run: |
        echo "::set-output name=java-version::%errorlevel%"
      shell: bash
