name: "Java Version"
description: "Set the latest Java version for the current gradle version found in the project"

outputs:
  java-version:
    description: "Java version set"
    value: ${{ steps.current-java-version.outputs.java-version }}

runs:
  using: "composite"
  steps:
    - name: Install Python 3
      uses: actions/setup-python@v1
      with:
        python-version: "3.x"

    - name: Try to reinstall dependancies
      run: pip install requests
      shell: bash

    - name: Execute command
      run: python ${{ github.action_path }}/main.py
      shell: bash

    - name: Output result from *nix
      id: unix-result
      if: runner.os != 'Windows'
      run: echo "::set-output name=java-version::$?"
      shell: bash

    - name: Output result from Windows
      id: windows-result
      if: runner.os == 'Windows'
      run: |
        echo "::set-output name=java-version::%errorlevel%"
      shell: bash

    - id: current-java-version
      run: |
        if [[ -z ${{ steps.unix-result.outputs.java-version || '' }} ]]
        then
          echo "::set-output name=java-version::${{ steps.unix-result.outputs.java-version }}"
        elif [[ -z ${{ steps.windows-result.outputs.java-version || '' }} ]]
        then
          echo "::set-output name=java-version::${{ steps.windows-result.outputs.java-version }}"
        else
          echo "::set-output name=java-version::-1"
        fi
      shell: bash
