name: Release new version

on:
  push:
    branches:
      - main

jobs:
  test-action:
    uses: daniele-tentoni/java-version-action/.github/workflows/test-action.yml@main

  test-script:
    uses: daniele-tentoni/java-version-action/.github/workflows/test-script.yml@main

  release:
    needs: [test-action, test-script]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}

      - name: Release using Semantic Releasing
        run: |
          npm install
          npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
