name: Test Action

on:
  pull_request:
    branches:
      - main
  workflow_call:

env:
  owner: daniele-tentoni
  repo: gradle-wrapper-example

jobs:
  # Fetch remote repo to get the most recent tag to use to test action.
  fetch:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.repo-version.outputs.version }}
    steps:
      - name: Fetch remote repo
        id: repo-version
        run: |
          repo=https://github.com/${{ env.owner }}/${{ env.repo }}.git
          v=$(git ls-remote --tags --sort=-v:refname $repo | cut -f 1 | head -n 1)
          echo "::set-output name=version::$v"

  test:
    needs: [fetch]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Checkout example gradle project
        uses: actions/checkout@v2
        with:
          repository: ${{ env.owner }}/${{ env.repo }}
          ref: ${{ needs.fetch.outputs.version }}
          path: ${{ env.repo }}

      - name: Run this action
        id: java-version-step
        uses: ./

      - name: Check the Java version
        if: runner.os != 'Windows'
        run: "[[ ${{ steps.java-version-step.outputs.java-version }} -eq 17 ]]"

      - name: Check the Java version
        if: runner.os == 'Windows'
        run: |
          if ( ${{ steps.java-version-step.outputs.java-version }} -eq 17 )
          {
            exit 0
          }
          exit 1
