name: Test Action

on:
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Create default properties file
        run: echo "version=7.3" >> gradle-wrapper.properties

      - name: Run this action
        id: java-version-step
        uses: ./

      - name: Check the Java version
        if: runner.os != 'Windows'
        run: "[[ ${{ steps.java-version-step.outputs.java-version }} -eq 17 ]]"

      - name: Check the Java version
        if: runner.os == 'Windows'
        run: |
          if ( ${{ steps.java-version-step.outputs.java-version }} -eq 17 )
          {
            exit 0
          }
          exit 1
